### ISSUE TITLE
error in make_perm_mat() 

### ISSUE THREAD

**Issue by ltipton** [borenstein-lab/MIMOSA#1]
In running the "main MIMOSA analysis" as part of the runMimosa.R script execution halts with the message: 

> Error in .Call("_mimosa_make_perm_mat", PACKAGE = "mimosa", nSamples,  : 
>   "_mimosa_make_perm_mat" not available for .Call() for package "mimosa"
> Calls: run_all_metabolites -> mantel_2sided -> make_perm_mat -> .Call

If I load the library mimosa into my R session, I can pull up the help page for make_perm_mat() but calling the function results in the following error message:

> Error in make_perm_mat() : could not find function "make_perm_mat"

Is there something else I need to do to make this run?

**Comment by cnoecker** [comment]
Hi,
`make_perm_mat` uses Rcpp, so that likely means something went wrong in your installation of that part of the package. Did you install using devtools in RStudio (recommended), or another way? What operating system are you using? Please also send the output of `devtools::session_info()` from the R session where it fails.

**Comment by ltipton** [comment]
I installed mimosa using devtools in R Studio and then was running runMimosa.R from the command line. I am running this on an Ubuntu 14.04 operating system. I tried to reinstall Rcpp but receive the same error message within RStudio that it "could not find function "make_perm_mat". The devtools::session_info results are as follows:

> Session info ------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.153)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       SystemV/HST10               
 date     2018-02-09                  

Packages ----------------------------------------------------------------
 package        * version  date      
 base           * 3.4.1    2017-07-08
 colorspace       1.3-2    2016-12-14
 compiler         3.4.1    2017-07-08
 cowplot          0.9.2    2017-12-17
 data.table       1.10.4-3 2017-10-27
 datasets       * 3.4.1    2017-07-08
 devtools         1.13.4   2017-11-09
 digest           0.6.15   2018-01-28
 ggnetwork        0.5.1    2016-03-25
 ggplot2          2.2.1    2016-12-30
 ggrepel          0.7.0    2017-09-29
 graphics       * 3.4.1    2017-07-08
 grDevices      * 3.4.1    2017-07-08
 grid             3.4.1    2017-07-08
 gtable           0.2.0    2016-02-26
 lazyeval         0.2.1    2017-10-29
 memoise          1.1.0    2017-04-21
 methods        * 3.4.1    2017-07-08
 mimosa         * 1.0.0    2018-02-06
 munsell          0.4.3    2016-02-13
 network          1.13.0   2015-09-19
 pillar           1.1.0    2018-01-14
 plyr             1.8.4    2016-06-08
 Rcpp             0.12.15  2018-01-20
 rlang            0.1.6    2017-12-21
 scales           0.5.0    2017-08-24
 sna              2.4      2016-08-08
 statnet.common   4.0.0    2017-08-16
 stats          * 3.4.1    2017-07-08
 tibble           1.4.2    2018-01-22
 tools            3.4.1    2017-07-08
 utils          * 3.4.1    2017-07-08
 withr            2.1.1    2017-12-19
 source                                
 local                                 
 CRAN (R 3.4.1)                        
 local                                 
 CRAN (R 3.4.1)                        
 cran (@1.10.4-)                       
 local                                 
 cran (@1.13.4)                        
 cran (@0.6.15)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 local                                 
 local                                 
 local                                 
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 local                                 
 Github (borenstein-lab/MIMOSA@b8ffd5f)
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 cran (@0.5.0)                         
 CRAN (R 3.4.1)                        
 CRAN (R 3.4.1)                        
 local                                 
 CRAN (R 3.4.1)                        
 local                                 
 local                                 
 cran (@2.1.1)  

Thanks for your help!

**Comment by cnoecker** [comment]
Okay, I was able to reproduce your error and find the problem - it looks like Rcpp changed the way exported functions are formatted and those changes didn't get pushed to the online repository. Reinstall mimosa now with `install_github("borenstein-lab/MIMOSA/mimosa", force=T)`. Let me know if it still doesn't work.
