### ISSUE TITLE
MIMOSA2 webserver not fount

### ISSUE THREAD

**Issue by ruchi19flowchart** [borenstein-lab/MIMOSA#2]
the link which have been provided is not working https://elbo-spice.gs.washington.edu/MIMOSA2shiny/
Below error I'm getting :
Not Found

The requested URL /MIMOSA2shiny/ was not found on this server.
Apache/2.2.15 (CentOS) Server at elbo-spice.gs.washington.edu Port 443

**Comment by cnoecker** [comment]
Apologies, the correct link is https://elbo-spice.gs.washington.edu/shiny/MIMOSA2shiny/ . You can also find more info on MIMOSA2 at http://borensteinlab.com/software_MIMOSA2.html . Thanks for pointing this out!
